spring:

  application:
    name: acnhdb
  profiles:
    active: dev
    # 启动的环境是 开发环境, 即lyb 环境
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com/ecnudbcourse/acnhdb/entity
