spring:
  datasource:
    url: jdbc:mysql://localhost:53306/acnh
    username: test # jcd环境
    password: StrongPassword123!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
